from robot.api.deco import keyword

def program_bitstream(): ...

def run_nbd_server(): ...

def run_tftp_server(): ...

@keyword('Boot u-boot SPL')
def boot_uboot_spl(): ...

@keyword('Boot u-boot .itb')
def boot_uboot_itb(): ...

@keyword('Boot Linux through tFTP')
def boot_linux_through_tftp(): ...
